[2024-03-19T11:11:01.319+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Crawler.your_task_id scheduled__2024-03-19T11:10:00+00:00 [queued]>
[2024-03-19T11:11:01.325+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Crawler.your_task_id scheduled__2024-03-19T11:10:00+00:00 [queued]>
[2024-03-19T11:11:01.325+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-19T11:11:01.334+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): your_task_id> on 2024-03-19 11:10:00+00:00
[2024-03-19T11:11:01.340+0000] {standard_task_runner.py:60} INFO - Started process 195 to run task
[2024-03-19T11:11:01.343+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'Crawler', 'your_task_id', 'scheduled__2024-03-19T11:10:00+00:00', '--job-id', '190', '--raw', '--subdir', 'DAGS_FOLDER/new_crawler.py', '--cfg-path', '/tmp/tmpx3f8t3h2']
[2024-03-19T11:11:01.345+0000] {standard_task_runner.py:88} INFO - Job 190: Subtask your_task_id
[2024-03-19T11:11:01.383+0000] {task_command.py:423} INFO - Running <TaskInstance: Crawler.your_task_id scheduled__2024-03-19T11:10:00+00:00 [running]> on host 26a0b219297f
[2024-03-19T11:11:01.450+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Xirano' AIRFLOW_CTX_DAG_ID='Crawler' AIRFLOW_CTX_TASK_ID='your_task_id' AIRFLOW_CTX_EXECUTION_DATE='2024-03-19T11:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-19T11:10:00+00:00'
[2024-03-19T11:34:28.326+0000] {local_task_job_runner.py:296} WARNING - DagRun timed out after 0:23:27.955045.
[2024-03-19T11:34:33.375+0000] {local_task_job_runner.py:296} WARNING - DagRun timed out after 0:23:33.003783.
[2024-03-19T11:34:33.376+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to skipped. Terminating instance.
[2024-03-19T11:34:33.380+0000] {process_utils.py:131} INFO - Sending 15 to group 195. PIDs of all processes in the group: [195]
[2024-03-19T11:34:33.381+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 195
[2024-03-19T11:34:33.382+0000] {taskinstance.py:2483} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-03-19T11:34:33.383+0000] {logging_mixin.py:188} INFO - ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
[2024-03-19T11:34:33.384+0000] {logging_mixin.py:188} INFO -  the error acuire in crawl data from TSETMS Task received SIGTERM signal
[2024-03-19T11:34:33.384+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-03-19T11:34:33.401+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=Crawler, task_id=your_task_id, execution_date=20240319T111000, start_date=20240319T111101, end_date=20240319T113433
[2024-03-19T11:34:33.438+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=195, status='terminated', exitcode=0, started='11:11:00') (195) terminated with exit code 0
